# -*- coding: utf-8 -*-
"""AI Demand Forecasting Restaurant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZxSdGKcJdgtv2lvDD6oewFcpWmgfzTu
"""

print("Hello Project")

import pandas as pd
import numpy as np

import pandas as pd

df = pd.read_csv("/content/demand_forecasting.csv")

print(df.head())
print(df.columns)

df['Date'] = pd.to_datetime(df['Date'])

df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Weekday'] = df['Date'].dt.weekday

df = df.dropna()

df = pd.get_dummies(df, columns=[
    'Category','Region','Weather Condition','Seasonality'
], drop_first=True)

df['Effective Price'] = df['Price'] * (1 - df['Discount']/100)
df['Stock Pressure'] = df['Units Ordered'] - df['Inventory Level']

X = df[['Day','Month','Weekday',
        'Inventory Level','Units Ordered',
        'Price','Discount','Promotion',
        'Competitor Pricing','Epidemic']]

y = df['Demand']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

!pip install xgboost

from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, pred)
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mse)

print("MAE:", mae)
print("RMSE:", rmse)

import matplotlib.pyplot as plt

importance = model.feature_importances_
features = X.columns

plt.barh(features, importance)
plt.title("Feature Importance")
plt.show()

# Recreate X from SAME df (important)
X_full = df[X.columns]

df['Predicted Demand'] = model.predict(X_full)

df['Suggested Inventory'] = df['Predicted Demand'] + 10

print(df[['Demand','Predicted Demand','Suggested Inventory']].head())